### ISSUE TITLE
Release binaries

### ISSUE THREAD

**Issue by kmturley** [antonok-edm/ampli-Fe#6]
Hi there, thanks for open-sourcing your code and releasing your plugin.

Would you be able to publish binaries for linux, mac and windows? So that every persons doesn't need to build it themselves? You can upload them as a GitHub release.

It's also possible to add a Github workflow which will build you plugin automatically for each platform in a pipeline. I don't have an example for Rust, but for VST3 plugins:
https://github.com/studiorack/studiorack-plugin-steinberg/blob/main/.github/workflows/release.yml#L28

Thanks!

**Comment by antonok-edm** [comment]
> I might steal the arch: x86-64 option for my own pipelines, always good to be specific.

Ha, hopefully someday I will add some builds for other architectures too!

> Only comment would be whether all plugins should be released in the same format. e.g. zip For consistency. But that's my personal preference.

This is a good point. I figured Linux and Windows could be packaged as-is since they're literally just single files, but looking back at it I also see that the Bitwig UI (and maybe other DAWs as well) displays the name of the plugin _file_ rather than the name provided in the plugin descriptor.

![2021-10-29-112918_344x35_scrot](https://user-images.githubusercontent.com/22821309/139484668-49216934-3ed7-4639-a618-01aaba3d1d62.png)

I'm going to update it to zip on all platforms so I can name the plugin file without a suffix.

> Congrats on implementing so quickly, I guess rust is more robust :)

It definitely helps that `cargo` is a fully-featured cross-platform dependency manager, build configuration tool, and compiler all in one package :smile:

**Comment by antonok-edm** [comment]
Initial releases are now available [here](https://github.com/antonok-edm/ampli-Fe/releases/tag/v0.1.0)! Thanks for the help @kmturley.

**Comment by kmturley** [comment]
No problem! Now that there are cross-platform binaries, I have added ampli-Fe to StudioRack!
https://studiorack.github.io/studiorack-site/plugins/studiorack_ampli-fe_ampli-fe

**Comment by antonok-edm** [comment]
Ooh, awesome website! Thanks for putting that together :smile:
