### ISSUE TITLE
What is VST2?

### ISSUE THREAD

**Issue by hoijui** [antonok-edm/ampli-Fe#9]
Could you please include a link to a meaningful VST2 page, the first time the string appears in the README?
Plus maybe also a tiny, short description of what it is, in-line, like: "... VST2 plugin (a virtual music studio) ...".

Like me, many people will come to this project because they saw it as an example on the wgpu website,
so the chance that they know what VST2 is is relatively low.

**Comment by antonok-edm** [comment]
@hoijui thanks, that's a good call. I [added](https://github.com/antonok-edm/ampli-Fe/commit/5fa734bd808e43d2c3a515c82f6739c65c547b81) a link to the wikipedia page, but also more importantly a link to the more recent deprecation notice (since technically VST2 is now discontinued).

Perhaps someday I will look into making a [CLAP](https://cleveraudio.org/) example, since that's a better modern alternative.

**Comment by hoijui** [comment]
peeerfect, thank you @antonok-edm ! :-)
